### PR TITLE
Normalize the config file to minimize noise later

### PR DESCRIPTION
**Pull request by kytrinyx**
We will be scripting a number of changes to the track configuration.
This runs configlet fmt, which ensures that any further changes can be minimized.

See https://github.com/exercism/meta/issues/95

### CODE REVIEW

**Comment by bdw429s** [comment]
We probably need to tweak the JSON formatting of the task runners that are used to create new exercises in this repo.  It doesn't use the exact same formatting of the configlet which is going to make this a constant back and forth.

**Comment by kytrinyx** [comment]
You could also potentially have the task runner run `configlet fmt` afterwards.

**Comment by bdw429s** [comment]
@kytrinyx Yes, I  had thought about that, but I kind of like the fact that `configlet` isn't required for anything since the CFML-based task runners are all you need to scaffold a new exercise.  And with the latest pull on this repo, the CFML task runners even handle the readme generation.  At the end of the day, it's a smell of sorts that the format of a data format, whose format shouldn't matter ends up, well... mattering.  i.e., any valid JSON should be just as good.  I guess it just boils down to the fact that we're using text-based diffing to manage data set comparisons.   Making the formatting of the task runners match configlet shouldn't be too hard.  I just need to nail down what's different and add settings to control those things since https://github.com/Ortus-Solutions/JSONPrettyPrint is a shared library which needs to still behave the same by default.

**Comment by kytrinyx** [comment]
There's some discussion in exercism/meta#95 about how this normalization degrades the readability of the configs.
Unfortunately, this means that I'm going to have to submit yet another normalization once that discussion concludes and we update the serializer.

I'm sorry about the noise, and any extra work that this is causing you!

Meanwhile, if you have any opinions on the topic, I'd appreciate it if you added your thoughts in exercism/meta#95

**Comment by bdw429s** [comment]
@kytrinyx For what it's worth, I just squashed the last two small differences in my CFML-based JSON formatting and the `configlet fmt` command.  (A space after each colon, and no whitespace between `[]`/`{}`.)  The CFML exercise scaffold will now generate JSON that follows the same format  and I also created a small CFML task runner to reformat the JSON file if necessary due to manual editing.  
```
CommandBox> task run formatConfig
```
These changes came in https://github.com/exercism/cfml/pull/71
I don't mind the work to do this.  It's sort of fun to figure it out, plus I like exercising CFML as much as possible in the track just to showcase its usefulness as a CLI scripting tool.  If the JSON format ever changes, I'll just update our task runner to match.

**Comment by bdw429s** [comment]
My thoughts have been applied to https://github.com/exercism/meta/issues/95 .  I hope it's not just fuel on a fire :)

**Comment by kytrinyx** [comment]
Thank you @bdw429s 🌷 

I really want to find the best balance in all of this. Your observations about square peg / round hole ring true. It's trade-offs all the way down!

**Pull request merged**
