### PR TITLE
Rename exercise hints file to follow convention

### PR DESCRIPTION
**Pull request by kytrinyx**
The convention is to use lowercase for the hints filename. The old (now deprecated) convention
was to put a 'HINTS.md' file directly in the exercise directory.

This track kind of combined the best of both worlds :)

Ref: https://github.com/exercism/meta/issues/94

### CODE REVIEW

**Comment by kytrinyx** [comment]
Since this is purely janitorial rather than language-specific, I'm going to go ahead and merge this.

**Comment by bdw429s** [comment]
Thanks. I'll need to update the exercise template that we use so future exercises follow the new pattern.

**Comment by kytrinyx** [comment]
The exercise template is updated in this PR

**Comment by bdw429s** [comment]
Doesn't look like it.  Here's the template file:
https://github.com/exercism/cfml/blob/master/tasks/exercise_template/.meta/HINTS.md

**Comment by kytrinyx** [comment]
Dangit. I was so sure that I had included it. Sorry about that!

**Comment by bdw429s** [comment]
No worries, I updated it so we're golden!

**Pull request merged**
